services:
  broker:
    container_name: redis_broker
    image: redis:latest
  web:
    container_name: django_web
    build:
      context: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - broker
  worker:
    container_name: celery_worker 
    build:
      context: .
    volumes:
      - ./src:/app/src
    env_file: 
      - .env
    depends_on:
      - broker
