name: django-celery

services:
  broker:
    image: redis:latest
  web:
    build:
      context: .
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app/src
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - broker
  worker:
    build:
      context: .
    command: celery --app=core.celery worker --loglevel=${CELERY_LOG_LEVEL:-info}
    environment: 
      - PYTHONPATH=/app/src
    volumes:
      - ./src:/app/src
    env_file: 
      - .env
    depends_on:
      - broker
